### ISSUE TITLE
IT DOESN'T BUILD

### ISSUE THREAD

**Issue by SEAPUNK** [OrdinaryMagician/aliceos-kernel#2]
IT KEEPS GIVING ME ERRORS I HTINK MY COMPUTER IS GOING TO EXPLODE WHAT IS GOIGN ON

**Comment by OrdinaryMagician** [comment]
Already fixed

**Comment by SEAPUNK** [comment]
oh no, my shitposts from years ago are coming back to me :rofl:

but cool, i wanted to check it out at some point

**Comment by BrokenMedjed** [comment]
it was my shitpost... look at #3

**Comment by SEAPUNK** [comment]
yeah well

**Comment by BrokenMedjed** [comment]
omegalul
