### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by sublok** [OrdinaryMagician/aliceos-kernel#3]
Can you post steps to compile in osx?

**Comment by OrdinaryMagician** [comment]
This project has been abandoned since 2014.

**Comment by codyharrington** [comment]
cute

**Comment by rxse** [comment]
marisa is cute

**Comment by sublok** [comment]
Ok.

**Comment by OrdinaryMagician** [comment]
ok

**Comment by BrokenMedjed** [comment]
(but it's true)

**Comment by fosu** [comment]
top 10 anime deaths

**Comment by OrdinaryMagician** [comment]
help

**Comment by OrdinaryMagician** [comment]
Haven't touched this darn thing in 5 years, but I guess I can just fix this.

**Comment by BrokenMedjed** [comment]
did I just necro a github repo from ~2 years ago

send medal nao
